vcpkg_fail_port_install(ON_TARGET "OSX")

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO microsoft/msquic
    REF 5f5bb5ccbf5fdf832d82914b3f69e160f9e562b9
    SHA512 e950db64d00f251f6b71b603fdb79d53e34ab01c7934a72ae3ad39a10867a478b5be87355be7162844721f1dee7bf7ef1a5c7540a7a689f04df86f6b777fd32a
)

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA

    OPTIONS
        -DQUIC_TLS=stub
        -DQUIC_BUILD_TEST=OFF
        -DQUIC_BUILD_TOOLS=OFF
)
vcpkg_build_cmake()

message(STATUS ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET})

file(COPY ${SOURCE_PATH}/src/inc/ DESTINATION ${CURRENT_PACKAGES_DIR}/include)
file(COPY ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg/bin/Debug/ DESTINATION ${CURRENT_PACKAGES_DIR}/debug/bin FILES_MATCHING PATTERN "msquic.dll")
file(COPY ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg/obj/Debug/ DESTINATION ${CURRENT_PACKAGES_DIR}/debug/lib FILES_MATCHING PATTERN "msquic.lib")
file(COPY ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg/bin/Debug/ DESTINATION ${CURRENT_PACKAGES_DIR}/debug/bin FILES_MATCHING PATTERN "msquic.pdb")

file(COPY ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/bin/Release/ DESTINATION ${CURRENT_PACKAGES_DIR}/bin FILES_MATCHING PATTERN "msquic.dll")
file(COPY ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/obj/Release/ DESTINATION ${CURRENT_PACKAGES_DIR}/lib FILES_MATCHING PATTERN "msquic.lib")
file(COPY ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/bin/Release/ DESTINATION ${CURRENT_PACKAGES_DIR}/bin FILES_MATCHING PATTERN "msquic.pdb")

file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/msquic RENAME copyright)